# Generated by Django 4.2.1 on 2023-06-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='assess_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
