# Generated by Django 4.2.1 on 2023-06-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newuser_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='contents',
            field=models.JSONField(default=list, null=True),
        ),
    ]
